name: deployment

on:
  pull_request:
    branches:
      - '*'
      - '!main'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install numpydoc
          pip install -e .
          pip install matplotlib
          pip install sphinx-autoapi==3.4.0
          pip install sphinx-book-theme==1.1.3
          pip install sphinx-gallery==0.18.0
          pip install pytest
      - name: Pytests
        if: success()
        run: |
          pytest tests
      - name: Sphinx build
        if: success()
        run: |
          sphinx-build -M html docs/source/ docs/_build/
